apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: common
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: emindsguardians/testdeploy:latest
        command: [ "npm" , "start" ]
        ports:
        - containerPort: 3000