apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: testenv
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: emindsguardians/testdeploy:latest
        command: [ "npm" , "start" ]
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: testenv
spec:
  type: LoadBalancer
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 3000